DROP DATABASE IF EXISTS mokkikodit;
CREATE DATABASE mokkikodit CHARACTER SET utf8mb4;
USE mokkikodit;

CREATE TABLE OSOITE (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Katuosoite VARCHAR(255) NOT NULL,
    Kaupunki VARCHAR(255) NOT NULL,
    Maa VARCHAR(255) NOT NULL,
    Postinumero INT NOT NULL
);

CREATE TABLE HENKILOKUNTA (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Kayttajatunnus VARCHAR(255) NOT NULL,
    Salasana VARCHAR(255) NOT NULL,
    Kayttoikeus VARCHAR(255) NOT NULL
);

CREATE TABLE ASIAKAS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Osoite_ID INT,
    Nimi VARCHAR(255) NOT NULL,
    Sahkoposti VARCHAR(255) NOT NULL,
    Puhelinnumero VARCHAR(20),
    FOREIGN KEY (Osoite_ID) REFERENCES OSOITE(ID)
);

CREATE TABLE MOKKI (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Osoite_id INT NOT NULL,
    Vuokrahinta FLOAT NOT NULL,
    Nimi VARCHAR(255) NOT NULL,
    Tila VARCHAR(50),
    FOREIGN KEY (Osoite_id) REFERENCES OSOITE(ID)
);

CREATE TABLE LASKU (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Viitenumero VARCHAR(255) NOT NULL,
    Erapaiva DATE NOT NULL,
    Maksaja VARCHAR(255) NOT NULL,
    Saaja VARCHAR(255) NOT NULL,
    Y_tunnus VARCHAR(255),
    ALV_prosentti FLOAT NOT NULL,
    Maara INT NOT NULL
);

CREATE TABLE VARAUS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Lasku_ID INT NOT NULL,
    Mokki_ID INT NOT NULL,
    Asiakas_ID INT NOT NULL,
    Aloituspaivamaara DATE NOT NULL,
    Paattymispaivamaara DATE NOT NULL,
    Henkilomaara INT NOT NULL,
    FOREIGN KEY (Lasku_ID) REFERENCES LASKU(ID),
    FOREIGN KEY (Mokki_ID) REFERENCES MOKKI(ID),
    FOREIGN KEY (Asiakas_ID) REFERENCES ASIAKAS(ID)
);